_wandb:
    value:
        cli_version: 0.21.4
        e:
            a4wb327xs3vv0jfac4rsys9ebuxh0om6:
                args:
                    - --method
                    - joint
                    - --model_name_or_path
                    - Qwen/Qwen2.5-1.5B
                    - --dataset_path
                    - data/processed/kug_dataset_all.jsonl
                    - --output_dir
                    - outputs/kug_overhaul
                    - --wandb_project
                    - kug_overhaul_qwen1.5b
                    - --num_epochs
                    - "50"
                    - --batch_size
                    - "14"
                    - --gradient_accumulation_steps
                    - "1"
                    - --learning_rate
                    - "2e-4"
                codePath: src/training/train_kug_overhaul.py
                codePathLocal: src/training/train_kug_overhaul.py
                cpu_count: 128
                cpu_count_logical: 128
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "1888556142592"
                        used: "51698323456"
                email: jerryma@smu.edu
                executable: /users/jerryma/.conda/envs/torch2.8/bin/python
                git:
                    commit: f66cb0d239d1f41b48c0c8e6c7fa0b597f54d57a
                    remote: https://github.com/JerMa88/faster-sft.git
                gpu: NVIDIA A100-SXM4-80GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-996d4042-eefa-885a-0538-bf6478bdee51
                host: bcm-dgxa100-0007
                memory:
                    total: "2164308234240"
                os: Linux-5.15.0-1083-nvidia-x86_64-with-glibc2.35
                program: /work/projects/mhahsler/course_recomm/allocation001/AI_Club/paper/faster-sft/src/training/train_kug_overhaul.py
                python: CPython 3.12.11
                root: /work/projects/mhahsler/course_recomm/allocation001/AI_Club/paper/faster-sft
                slurm:
                    cluster_name: mp
                    conf: /cm/shared/apps/slurm/var/etc/slurm/slurm.conf
                    cpus_on_node: "16"
                    cpus_per_task: "16"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: mhahsler_course_recomm_0001
                    job_cpus_per_node: "16"
                    job_end_time: "1786520121"
                    job_gid: "999999"
                    job_gpus: "1"
                    job_id: "474139"
                    job_name: kug_train
                    job_nodelist: bcm-dgxa100-0007
                    job_num_nodes: "1"
                    job_partition: batch
                    job_qos: normal
                    job_start_time: "1786476921"
                    job_uid: "148858139"
                    job_user: jerryma
                    jobid: "474139"
                    localid: "0"
                    mem_per_node: "81920"
                    nnodes: "1"
                    node_aliases: (null)
                    nodeid: "0"
                    nodelist: bcm-dgxa100-0007
                    nprocs: "1"
                    ntasks: "1"
                    prio_process: "10"
                    procid: "0"
                    scontrol: /cm/shared/apps/slurm/current/bin/scontrol
                    sinfo: /cm/shared/apps/slurm/current/bin/sinfo
                    submit_dir: /work/projects/mhahsler/course_recomm/allocation001/AI_Club/paper/faster-sft
                    submit_host: slogin-01
                    task_pid: "1193206"
                    tasks_per_node: "1"
                    topology_addr: bcm-dgxa100-0007
                    topology_addr_pattern: node
                    working_cluster: mp:mpcm1:6817:9984:109
                startedAt: "2026-08-11T19:35:31.521182Z"
                writerId: a4wb327xs3vv0jfac4rsys9ebuxh0om6
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 71
                - 98
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 71
                - 98
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.11
            "5": 0.21.4
            "6": 5.14.1
            "8":
                - 2
            "12": 0.21.4
            "13": linux-x86_64
base_model:
    value: Qwen/Qwen2.5-1.5B
batch_size:
    value: 14
gradient_accumulation_steps:
    value: 1
learning_rate:
    value: 0.0002
lora_alpha:
    value: 32
lora_r:
    value: 16
method:
    value: joint
num_epochs:
    value: 50
